services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - aspire
    restart: always
    depends_on:
      - webapi
      - minio

  webapi:
    ports: []   

  minio:
    ports: []

networks:
  aspire:
    external: false

volumes:
  caddy_data:
  caddy_config: