<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" Version="2.0.1" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
      <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.7" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Brew.Domain\Brew.Domain.csproj" />
      <ProjectReference Include="..\Brew.Infrastructure\Brew.Infrastructure.csproj" />
      <ProjectReference Include="..\Brew.Shared\Brew.Shared.csproj" />
    </ItemGroup>

</Project>
