<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Brew.MigrationService-a73db2ea-4a11-43f9-8fba-b80a384df300</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChaychiMenu.Infrastructure\ChaychiMenu.Infrastructure.csproj" />
      <ProjectReference Include="..\ChaychiMenu.ServiceDefaults\ChaychiMenu.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
